<?xml version="1.0" encoding="utf-8"?><Database Name="linqptc" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=RT-LT-280\SQL2K8;Initial Catalog=linqptc;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="linqptcConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="item_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="amount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Item" Member="Order" ThisKey="order_id" OtherKey="order_id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Item" Member="Items" ThisKey="order_id" OtherKey="order_id" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Salesmen" Member="Salesmens">
    <Type Name="Salesmen">
      <Column Name="salesman_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="salesman_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="code" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>